import {ProjectRuntime,norm,ext,classify,resolve,mime} from './project-engine.js';
import {DEVICES,deviceCss} from './device-engine.js';
import {auditProject,compareAudits} from './audit-engine.js';
import {Storage} from './storage.js';
import {loadProviderSettings,saveProviderSettings,providerSummary} from './provider-settings.js';

const $=id=>document.getElementById(id);
const runtime=new ProjectRuntime();
const state={current:null,mode:'desktop',adapt:false,scale:1,runtimeErrors:[],audit:null,compare:null,fitMode:'width',desktopWidth:1440,shots:[],captureWaiters:new Map(),renderScore:null};
const frame=$('frame'),stage=$('desktopStage'),wrap=$('stageWrap'),shell=$('viewerShell'),main=document.querySelector('.main'),auditRail=$('auditRail');

function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function status(s){$('statusBadge').textContent=s}
function notice(s){$('notice').textContent=s;$('notice').classList.toggle('hidden',!s)}
function bytes(n){if(n<1024)return`${n} B`;if(n<1048576)return`${(n/1024).toFixed(1)} KB`;return`${(n/1048576).toFixed(1)} MB`}
function clearRuntimeUrls(){for(const [k,u] of [...runtime.urls])if(k.startsWith('render:')){URL.revokeObjectURL(u);runtime.urls.delete(k)}}
function fileDescription(name){const lower=name.toLowerCase(),e=ext(name);if(/(^|\/)index\.html?$/.test(lower))return'The starting page that opens the website.';if(/app\.(tsx|jsx|js|ts)$/.test(lower))return'One of the main files that puts the app screens together.';if(/main\.(tsx|jsx|js|ts)$/.test(lower))return'Starts the app and connects it to the page.';if(lower.endsWith('package.json'))return'A list of the code tools this project needs.';if(lower.includes('vite.config'))return'Instructions for how this website is built.';if(lower.includes('electron')||/(^|\/)main\.c?js$/.test(lower))return'Helps a desktop app start and talk to the computer.';if(/component|components/.test(lower))return'A reusable piece of a screen, like a table, menu, card, or button area.';if(e==='css')return'Controls colors, spacing, fonts, and sizes.';if(['js','mjs','ts','tsx','jsx'].includes(e))return'Program code that controls what the app does.';if(['png','jpg','jpeg','gif','webp','svg','ico'].includes(e))return'An image or icon used by the project.';if(['woff','woff2','ttf','otf'].includes(e))return'A font used to draw words on the screen.';if(e==='json')return'A small data or settings file the app reads.';if(e==='pdf')return'A PDF document included with the project.';if(e==='md'||/^readme/i.test(name.split('/').pop()))return'Notes that explain the project.';return'A supporting file used by this project.'}
function simpleProject(meta){if(meta.type==='HTML website')return'This is a website that can usually open right away.';if(meta.type==='Multi-page website')return`This is a website with ${meta.pageCount} separate page files. I connect them so you can move around without extracting it first.`;if(meta.type==='Vite web application'||meta.type==='React/Node application'||meta.type==='React-style source project')return'This is a website app made from many code pieces. I build those pieces together so you can see the real screen.';if(meta.type==='Electron application')return'This is a desktop app. I can test its website-style screen here and separate the computer-only parts.';if(meta.type==='Python project')return'This is a Python program. Some parts need a computer-side runner before the full app can be shown.';return'This project contains several kinds of files. I map them and explain what each part does.'}
function refreshFiles(){const el=$('fileList');el.innerHTML='';const names=[...runtime.files.keys()].sort();$('fileCountLabel').textContent=`${names.length} file${names.length===1?'':'s'}`;if(!names.length){el.innerHTML='<div class="small">No files loaded yet.</div>';$('pageTabs').innerHTML='';return}for(const n of names){const f=runtime.files.get(n),b=document.createElement('button');b.className='file-item'+(state.current===n?' active':'');b.title=n;b.innerHTML=`<span class="file-path">${esc(n)}</span><span class="file-desc">${esc(fileDescription(n))}</span><span class="file-meta">${esc(f.type||mime(n))} • ${bytes(f.size)}</span>`;b.onclick=()=>select(n);el.appendChild(b)}const pages=names.filter(n=>/\.html?$/i.test(n));$('pageTabs').innerHTML=pages.length>1?pages.map(p=>`<button class="tab ${state.current===p?'active':''}" data-page="${esc(p)}">${esc(p.split('/').pop())}</button>`).join(''):'';document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>select(b.dataset.page))}
function renderProjectSummary(){const meta=classify(runtime.files);$('projectSummary').innerHTML=`<strong>${esc(simpleProject(meta))}</strong><div class="small provider-note">${meta.fileCount} file${meta.fileCount===1?'':'s'} found${meta.pageCount?` • ${meta.pageCount} page file${meta.pageCount===1?'':'s'}`:''}.</div><details class="mini-details"><summary>Technical details</summary><div class="small">Detected as: ${esc(meta.type)}<br>Needs: ${esc(meta.runtime)}<br>Starting file: ${esc(runtime.entry()||'not found')}</div></details>`;return meta}
function waitFor(type,timeout=10000){return new Promise(resolve=>{const timer=setTimeout(()=>{state.captureWaiters.delete(type);resolve(false)},timeout);state.captureWaiters.set(type,payload=>{clearTimeout(timer);state.captureWaiters.delete(type);resolve(payload||true)})})}
async function loadProject(list,{skipConfirm=false}={}){if(!list?.length)return;if(runtime.files.size&&!skipConfirm&&!confirm('Replace the current temporary project? The older audit will stay in history for comparison.'))return;status('Opening…');notice('');state.runtimeErrors=[];state.audit=null;state.compare=null;state.current=null;state.shots=[];state.renderScore=null;renderGallery();try{await runtime.addFiles(list);refreshFiles();const meta=renderProjectSummary();status(`${meta.fileCount} files`);const entry=runtime.entry();if(entry)await select(entry);await runAudit()}catch(e){status('Could not open');notice('I could not open this project. '+e.message)}}
async function select(name){const clean=norm(name),f=runtime.files.get(clean);if(!f)return;state.current=clean;state.renderScore=null;refreshFiles();status('Building screen…');clearRuntimeUrls();const e=ext(clean);try{if(/html?/.test(e)){const inject=state.adapt?deviceCss(state.mode):'';const src=await runtime.htmlRewrite(await f.text(),clean,inject);const u=URL.createObjectURL(new Blob([src],{type:'text/html'}));runtime.urls.set('render:'+clean,u);frame.removeAttribute('srcdoc');const ready=waitFor('debooger-render-ready',14000);await new Promise(resolve=>{const timer=setTimeout(resolve,2500);frame.onload=()=>{clearTimeout(timer);resolve()};frame.src=u});const result=await ready;if(result?.score)state.renderScore=result.score}else if((f.type||'').startsWith('image/')||['png','jpg','jpeg','gif','webp','svg','ico'].includes(e)){const u=await runtime.objectUrl(clean);frame.srcdoc=`<!doctype html><html><body style="margin:0;background:white"><img src="${u}" style="max-width:100%;height:auto;display:block;margin:20px auto"></body></html>`}else if(e==='pdf'){frame.removeAttribute('srcdoc');frame.src=await runtime.objectUrl(clean)}else{const t=await f.text();frame.srcdoc=`<!doctype html><html><body style="margin:0"><pre style="white-space:pre-wrap;word-break:break-word;margin:0;padding:16px;font:13px/1.5 ui-monospace;background:#101317;color:#e7edf3;min-height:100vh">${esc(t)}</pre></body></html>`}status('Ready');applyDevice()}catch(err){status('Open problem');notice(err.message||String(err));frame.srcdoc=`<pre style="white-space:pre-wrap;padding:16px">${esc(String(err))}</pre>`}}
function deviceSize(){return state.mode==='desktop'?{...DEVICES.desktop,width:state.desktopWidth}:DEVICES[state.mode]}
function applyDevice(){const d=deviceSize();stage.style.width=d.width+'px';stage.style.height=d.height+'px';frame.style.width=d.width+'px';frame.style.height=d.height+'px';document.querySelectorAll('.device-btn').forEach(b=>b.classList.toggle('active',b.dataset.device===state.mode));$('desktopWidth').disabled=state.mode!=='desktop';applyFit()}
function applyFit(){requestAnimationFrame(()=>{const d=deviceSize(),availableW=Math.max(280,shell.clientWidth-4),availableH=Math.max(300,shell.clientHeight-4);state.scale=state.fitMode==='actual'?1:state.fitMode==='page'?Math.min(1,availableW/d.width,availableH/d.height):Math.min(1,availableW/d.width);stage.style.transform=`scale(${state.scale})`;wrap.style.width=(d.width*state.scale)+'px';wrap.style.height=(d.height*state.scale)+'px'})}
async function setDevice(mode){state.mode=mode;state.adapt=$('adaptToggle').checked;applyDevice();if(state.current)await select(state.current)}
function setFit(mode){state.fitMode=mode;applyFit()}
async function captureCurrent(label,states=false){if(!state.current||!/\.html?$/i.test(state.current))return false;const done=states?'debooger-states-finished':'debooger-capture-finished',waiting=waitFor(done,states?20000:12000);frame.contentWindow?.postMessage({type:states?'debooger-capture-states':'debooger-capture',label},'*');return waiting}
async function captureAuditScreens(){state.shots=[];renderGallery();const pages=[...runtime.files.keys()].filter(n=>/\.html?$/i.test(n));if(!pages.length)return 0;const start=state.current;for(let i=0;i<pages.length;i++){await select(pages[i]);status(`Photographing ${i+1}/${pages.length}…`);await captureCurrent(pages[i]);if(i===0)await captureCurrent(pages[i],true)}if(start&&runtime.files.has(start))await select(start);return state.shots.length}
function renderLooksReal(){const s=state.renderScore;return !!s&&(s.text>=20||s.visible>=8)&&s.width>20&&s.height>20}
async function runAudit(){if(!runtime.files.size)return;status('Checking everything…');const meta=classify(runtime.files),audit=await auditProject(runtime.files,meta,state.runtimeErrors),previous=Storage.history()[0]||null;state.audit=audit;state.compare=compareAudits(previous,audit);renderAudit();let shotCount=0;if(renderLooksReal()||!['Vite web application','React/Node application','React-style source project'].includes(meta.type))shotCount=await captureAuditScreens();audit.screenshotCount=shotCount;audit.visualComplete=shotCount>0;Storage.pushAudit(audit);renderHistory();if(shotCount){status('Audit complete');notice('')}else{status('Code checked • visual test incomplete');notice('I checked the files, but I did not get a trustworthy real-screen picture yet, so the visual test is not marked complete.')};renderAudit()}
function renderAudit(){const a=state.audit;if(!a)return;const cls=a.score>=90?'good':a.score>=70?'warn':'bad';$('scoreBox').innerHTML=`<div class="score ${cls}">${a.score}</div><div class="small">${esc(a.verdict)}${a.screenshotCount!=null?` • ${a.screenshotCount} screenshot${a.screenshotCount===1?'':'s'}`:''}</div>`;$('metrics').innerHTML=`<div class="metric"><b>${a.meta.fileCount}</b><span>Files checked</span></div><div class="metric"><b>${a.findings.length}</b><span>Things to review</span></div><div class="metric"><b>${a.good.length}</b><span>Good checks</span></div><div class="metric"><b>${a.meta.pageCount}</b><span>Page files</span></div>`;const top=a.findings.slice(0,30);$('findings').innerHTML=top.length?top.map(f=>`<details class="finding ${f.severity==='critical'||f.severity==='error'?'bad':f.severity==='warning'?'warn':'good'}"><summary><strong>${esc(f.title)}</strong><div class="simple-line">${esc(f.plain)}</div></summary><p>${f.file?`File: ${esc(f.file)}${f.line?` • line ${f.line}`:''}<br>`:''}${f.technical?`Developer detail: ${esc(f.technical)}`:'Tap only when you need the technical reason.'}</p></details>`).join(''):'<div class="finding good"><summary><strong>No obvious source-code problems found</strong><div class="simple-line">The automatic code checks did not find a clear problem.</div></summary></div>';if(state.compare){$('compareBox').classList.remove('hidden');$('compareBox').innerHTML=`<details class="finding ${state.compare.delta>=0?'good':'warn'}"><summary><strong>${esc(state.compare.recommendation)}</strong><div class="simple-line">Tap to see the numbers behind this recommendation.</div></summary><p>Older score: ${state.compare.previousScore} • This score: ${state.compare.currentScore} • Fixed: ${state.compare.fixedCount} • New problems: ${state.compare.newIssueCount}</p></details>`}else $('compareBox').classList.add('hidden');syncMobileResults()}
function renderGallery(){$('shotCount').textContent=String(state.shots.length);$('gallery').innerHTML=state.shots.length?state.shots.map((s,i)=>`<button class="shot" data-shot="${i}"><img src="${s.data}" alt="${esc(s.label)}"><span>${esc(s.label)}</span></button>`).join(''):'<div class="small">Screenshots will appear automatically during the audit.</div>';document.querySelectorAll('#gallery [data-shot]').forEach(b=>b.onclick=()=>openShot(Number(b.dataset.shot)));syncMobileResults()}
function openShot(i){const s=state.shots[i];if(!s)return;$('shotTitle').textContent=s.label;$('shotImage').src=s.data;$('shotModal').classList.remove('hidden')}
function closeShot(){$('shotModal').classList.add('hidden');$('shotImage').removeAttribute('src')}
function syncMobileResults(){const host=$('mobileResultsHost');if(!host||!auditRail)return;host.innerHTML=auditRail.innerHTML;host.querySelectorAll('[id]').forEach(el=>el.removeAttribute('id'));host.querySelectorAll('[data-shot]').forEach(b=>b.onclick=()=>openShot(Number(b.dataset.shot)))}
function openResults(){syncMobileResults();$('resultsModal').classList.remove('hidden')}
function closeResults(){$('resultsModal').classList.add('hidden')}
function renderHistory(){const h=Storage.history();$('history').innerHTML=h.length?h.slice(0,6).map(x=>`<div class="history-item"><strong>${esc(simpleProject(x.meta))}</strong><div class="small">${new Date(x.createdAt).toLocaleString()} • Score ${x.score}${x.screenshotCount!=null?` • ${x.screenshotCount} screenshots`:''}</div></div>`).join(''):'<div class="small">No older audits saved on this device.</div>'}
function buildReport(){const a=state.audit;if(!a)return'No audit has been run yet.';let s=`DEBOOGER2000 AUDIT\n\nWHAT THIS IS\n${simpleProject(a.meta)}\n${a.meta.fileCount} files, ${a.meta.pageCount} page files\n\nSCORE\n${a.score}/100 — ${a.verdict}\nSCREENSHOTS\n${state.shots.length}\n\nGOOD\n${a.good.map(x=>'• '+x).join('\n')||'• No positive checks recorded'}\n\nWHAT NEEDS ATTENTION\n`;s+=a.findings.map((f,i)=>`${i+1}. ${f.title}\n   ${f.plain}${f.file?`\n   File: ${f.file}${f.line?` line ${f.line}`:''}`:''}${f.technical?`\n   Developer detail: ${f.technical}`:''}`).join('\n\n')||'No obvious issues found.';if(state.compare)s+=`\n\nVERSION COMPARISON\n${state.compare.recommendation}\nOlder: ${state.compare.previousScore} | Current: ${state.compare.currentScore} | Fixed: ${state.compare.fixedCount} | New: ${state.compare.newIssueCount}`;return s}
async function copyReport(){try{await navigator.clipboard.writeText(buildReport());status('Copied')}catch{const ta=document.createElement('textarea');ta.value=buildReport();document.body.appendChild(ta);ta.select();document.execCommand('copy');ta.remove();status('Copied')}}
function downloadReport(){const b=new Blob([buildReport()],{type:'text/plain'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='debooger2000-audit.txt';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function renderProviders(){const p=loadProviderSettings();$('groqEnabled').checked=!!p.groq?.enabled;$('groqKey').value=p.groq?.key||'';$('googleEnabled').checked=!!p.google?.enabled;$('googleKey').value=p.google?.key||'';$('providerStatus').textContent=providerSummary(p)}
function saveProviders(){const p={groq:{enabled:$('groqEnabled').checked,key:$('groqKey').value.trim()},google:{enabled:$('googleEnabled').checked,key:$('googleKey').value.trim()}};saveProviderSettings(p);$('providerStatus').textContent=providerSummary(p);status('AI setting ready')}
function clearProject(){if(runtime.files.size&&!confirm('Clear this temporary project? Older audit history will stay.'))return;runtime.clear();state.current=null;state.runtimeErrors=[];state.audit=null;state.compare=null;state.shots=[];state.renderScore=null;refreshFiles();renderGallery();$('projectSummary').innerHTML='<div class="small">Open something and I will explain it in simple English.</div>';$('scoreBox').innerHTML='<div class="score">—</div><div class="small">Open a project to begin.</div>';$('metrics').innerHTML='';$('findings').innerHTML='<div class="small">Problems will be explained here in simple English. Tap one for the detailed reason.</div>';$('compareBox').classList.add('hidden');frame.srcdoc=welcomeHtml();notice('');status('Ready')}
function welcomeHtml(){return'<!doctype html><html><body style="font-family:Inter,system-ui;padding:42px"><h1 style="font-size:24px">debooger2000</h1><p>Open a project to see the real pages, check the files, and explain what needs attention.</p></body></html>'}
function openPasteModal(){$('moreModal').classList.add('hidden');$('pasteModal').classList.remove('hidden');if(navigator.clipboard?.readText)navigator.clipboard.readText().then(t=>{if(!t)return;if(/^https?:\/\//i.test(t.trim())){$('pasteLink').value=t.trim();switchPaste('link')}else if(!$('pasteText').value)$('pasteText').value=t}).catch(()=>{})}
function closePasteModal(){$('pasteModal').classList.add('hidden')}
function switchPaste(mode){document.querySelectorAll('.paste-tab').forEach(b=>b.classList.toggle('active',b.dataset.paste===mode));$('pasteTextPanel').classList.toggle('hidden',mode!=='text');$('pasteLinkPanel').classList.toggle('hidden',mode!=='link')}
async function openPastedText(){const text=$('pasteText').value;if(!text.trim())return;const type=$('pasteType').value,name=`pasted.${type}`,file=new File([text],name,{type:mime(name)});closePasteModal();await loadProject([file])}
async function openPastedLink(){const url=$('pasteLink').value.trim();if(!/^https?:\/\//i.test(url)){notice('Paste a full web link.');return}status('Opening link…');try{const res=await fetch(url,{credentials:'omit'});if(!res.ok)throw new Error(`The link returned ${res.status}`);const blob=await res.blob();let name='download';try{name=decodeURIComponent(new URL(url).pathname.split('/').pop()||'download')}catch{}if(!ext(name)){if(blob.type.includes('zip'))name+='.zip';else if(blob.type.includes('html'))name+='.html';else name+='.bin'}closePasteModal();await loadProject([new File([blob],name,{type:blob.type||mime(name)})])}catch{status('Link blocked');notice('I could not open that link directly. Open or share the actual file instead.')}}
async function toggleFullScreen(){const entering=!main.classList.contains('viewer-full');main.classList.toggle('viewer-full',entering);document.body.classList.toggle('full-active',entering);$('exitFullBtn').classList.toggle('hidden',!entering);if(entering&&document.documentElement.requestFullscreen)try{await document.documentElement.requestFullscreen()}catch{}if(!entering&&document.fullscreenElement)try{await document.exitFullscreen()}catch{}setTimeout(applyFit,100)}
function openMore(){$('moreModal').classList.remove('hidden')}
function closeMore(){$('moreModal').classList.add('hidden')}
window.addEventListener('message',e=>{const d=e.data||{};if(d.type==='debooger-nav'){const p=norm(resolve(d.base,d.href));if(runtime.files.has(p))select(p)}else if(d.type==='debooger-runtime-error'){state.runtimeErrors.push(d);status('Running problem found')}else if(d.type==='debooger-screenshot'&&d.data){state.shots.push({label:d.label||'Screen',data:d.data,score:d.score||null});renderGallery()}else if(d.type==='debooger-screenshot-error'){notice('A screen image could not be captured: '+d.message)}if(state.captureWaiters.has(d.type))state.captureWaiters.get(d.type)(d)});
['dragenter','dragover'].forEach(v=>$('dropzone').addEventListener(v,e=>{e.preventDefault();$('dropzone').classList.add('drag')}));['dragleave','drop'].forEach(v=>$('dropzone').addEventListener(v,e=>{e.preventDefault();$('dropzone').classList.remove('drag')}));
$('dropzone').addEventListener('drop',e=>loadProject(e.dataTransfer.files));$('fileInput').onchange=e=>loadProject(e.target.files);$('folderInput').onchange=e=>loadProject(e.target.files);$('openBtn').onclick=()=>$('fileInput').click();$('folderBtn').onclick=()=>$('folderInput').click();$('pasteInlineBtn').onclick=openPasteModal;$('clearInlineBtn').onclick=()=>{closeMore();clearProject()};$('clearBtn').onclick=clearProject;$('auditBtn').onclick=runAudit;$('copyBtn').onclick=copyReport;$('downloadBtn').onclick=downloadReport;$('adaptToggle').onchange=()=>setDevice(state.mode);$('saveProviders').onclick=saveProviders;$('pasteBtn').onclick=openPasteModal;$('moreBtn').onclick=openMore;$('closeMoreBtn').onclick=closeMore;$('moreModal').addEventListener('click',e=>{if(e.target===$('moreModal'))closeMore()});$('closePasteBtn').onclick=closePasteModal;$('pasteModal').addEventListener('click',e=>{if(e.target===$('pasteModal'))closePasteModal()});document.querySelectorAll('.paste-tab').forEach(b=>b.onclick=()=>switchPaste(b.dataset.paste));$('openPasteTextBtn').onclick=openPastedText;$('openPasteLinkBtn').onclick=openPastedLink;$('fullBtn').onclick=toggleFullScreen;$('exitFullBtn').onclick=toggleFullScreen;$('fitWidthBtn').onclick=()=>setFit('width');$('fitPageBtn').onclick=()=>setFit('page');$('actualBtn').onclick=()=>setFit('actual');$('desktopWidth').onchange=e=>{state.desktopWidth=Number(e.target.value)||1440;applyDevice()};document.querySelectorAll('.device-btn').forEach(b=>b.onclick=()=>setDevice(b.dataset.device));$('closeShotBtn').onclick=closeShot;$('shotModal').addEventListener('click',e=>{if(e.target===$('shotModal'))closeShot()});$('openResultsBtn').onclick=openResults;$('closeResultsBtn').onclick=closeResults;$('resultsModal').addEventListener('click',e=>{if(e.target===$('resultsModal'))closeResults()});window.addEventListener('resize',applyFit);document.addEventListener('fullscreenchange',()=>{if(!document.fullscreenElement&&main.classList.contains('viewer-full')&&document.fullscreenEnabled){main.classList.remove('viewer-full');document.body.classList.remove('full-active');$('exitFullBtn').classList.add('hidden');applyFit()}});
renderHistory();renderProviders();refreshFiles();renderGallery();applyDevice();frame.srcdoc=welcomeHtml();