import {ProjectRuntime,norm,ext,classify,resolve,mime} from './project-engine.js';
import {DEVICES,deviceCss} from './device-engine.js';
import {auditProject,compareAudits} from './audit-engine.js';
import {Storage} from './storage.js';
import {loadProviderSettings,saveProviderSettings,providerSummary} from './provider-settings.js';

const $=id=>document.getElementById(id);const runtime=new ProjectRuntime();const state={current:null,mode:'desktop',adapt:false,scale:1,runtimeErrors:[],audit:null,compare:null};const frame=$('frame'),stage=$('desktopStage'),wrap=$('stageWrap'),shell=$('viewerShell');
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function status(s){$('statusBadge').textContent=s}
function notice(s){$('notice').textContent=s;$('notice').classList.toggle('hidden',!s)}
function bytes(n){if(n<1024)return n+' B';if(n<1048576)return(n/1024).toFixed(1)+' KB';return(n/1048576).toFixed(1)+' MB'}
function refreshFiles(){const el=$('fileList');el.innerHTML='';const names=[...runtime.files.keys()].sort();if(!names.length){el.innerHTML='<div class="small">No files loaded yet.</div>';return}for(const n of names){const b=document.createElement('button');b.className='file-item'+(state.current===n?' active':'');b.textContent=n;b.onclick=()=>select(n);el.appendChild(b)}const pages=names.filter(n=>/\.html?$/i.test(n));$('pageTabs').innerHTML=pages.length>1?pages.map(p=>`<button class="tab ${state.current===p?'active':''}" data-page="${esc(p)}">${esc(p.split('/').pop())}</button>`).join(''):'';document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>select(b.dataset.page))}
function renderProjectSummary(){const meta=classify(runtime.files);$('projectSummary').innerHTML=`<div class="finding good"><strong>${esc(meta.type)}</strong><p>${meta.fileCount} files • ${meta.pageCount} page${meta.pageCount===1?'':'s'} • ${esc(meta.runtime)}</p></div>`;return meta}
async function addFiles(list){if(!list?.length)return;status('Opening project…');notice('');state.runtimeErrors=[];try{await runtime.addFiles(list);refreshFiles();const meta=renderProjectSummary();status(`${meta.fileCount} files loaded`);const entry=runtime.entry();if(entry)await select(entry);await runAudit()}catch(e){status('Could not open');notice('This project could not be opened: '+e.message)}}
async function select(name){const f=runtime.files.get(norm(name));if(!f)return;state.current=norm(name);refreshFiles();status('Rendering…');const e=ext(name);try{if(/html?/.test(e)){const inject=state.adapt?deviceCss(state.mode):'';const src=await runtime.htmlRewrite(await f.text(),name,inject);const u=URL.createObjectURL(new Blob([src],{type:'text/html'}));runtime.urls.set('render:'+name,u);frame.removeAttribute('srcdoc');frame.src=u}else if((f.type||'').startsWith('image/')||['png','jpg','jpeg','gif','webp','svg','ico'].includes(e)){const u=await runtime.objectUrl(name);frame.srcdoc=`<html><body style="margin:0;background:white"><img src="${u}" style="max-width:100%;height:auto;display:block;margin:20px auto"></body></html>`}else if(e==='pdf'){frame.removeAttribute('srcdoc');frame.src=await runtime.objectUrl(name)}else{const t=await f.text();frame.srcdoc=`<html><body style="margin:0"><pre style="white-space:pre-wrap;word-break:break-word;margin:0;padding:16px;font:13px/1.5 ui-monospace;background:#101317;color:#e7edf3;min-height:100vh">${esc(t)}</pre></body></html>`}status('Ready');applyDevice()}catch(err){status('Render error');frame.srcdoc=`<pre>${esc(String(err))}</pre>`}}
function applyDevice(){const d=DEVICES[state.mode];stage.style.width=d.width+'px';frame.style.width=d.width+'px';frame.style.height=d.height+'px';document.querySelectorAll('.device-btn').forEach(b=>b.classList.toggle('active',b.dataset.device===state.mode));fit()}
function fit(){requestAnimationFrame(()=>{const d=DEVICES[state.mode];const available=Math.max(300,shell.clientWidth-4);state.scale=Math.min(1,available/d.width);stage.style.transform=`scale(${state.scale})`;wrap.style.width=(d.width*state.scale)+'px';wrap.style.height=(d.height*state.scale)+'px'})}
async function setDevice(mode){state.mode=mode;state.adapt=$('adaptToggle').checked;applyDevice();if(state.current)await select(state.current)}
async function runAudit(){if(!runtime.files.size)return;status('Auditing…');const meta=classify(runtime.files);const audit=await auditProject(runtime.files,meta,state.runtimeErrors);const previous=Storage.history()[0]||null;state.audit=audit;state.compare=compareAudits(previous,audit);Storage.pushAudit(audit);renderAudit();renderHistory();status('Audit complete')}
function renderAudit(){const a=state.audit;if(!a)return;const cls=a.score>=90?'good':a.score>=70?'warn':'bad';$('scoreBox').innerHTML=`<div class="score ${cls}">${a.score}</div><div class="small">${esc(a.verdict)}</div>`;$('metrics').innerHTML=`<div class="metric"><b>${a.meta.fileCount}</b><span>Files</span></div><div class="metric"><b>${a.findings.length}</b><span>Findings</span></div><div class="metric"><b>${a.good.length}</b><span>Good checks</span></div><div class="metric"><b>${a.meta.pageCount}</b><span>Pages</span></div>`;const top=a.findings.slice(0,20);$('findings').innerHTML=top.length?top.map(f=>`<div class="finding ${f.severity==='critical'||f.severity==='error'?'bad':f.severity==='warning'?'warn':'good'}"><strong>${esc(f.title)}</strong><p>${esc(f.plain)}${f.file?`<br><span class="tag">${esc(f.file)}${f.line?':'+f.line:''}</span>`:''}</p></div>`).join(''):'<div class="finding good"><strong>No obvious problems found</strong><p>The automatic checks did not find a clear issue in the source that was scanned.</p></div>';if(state.compare){$('compareBox').classList.remove('hidden');$('compareBox').innerHTML=`<div class="finding ${state.compare.delta>=0?'good':'warn'}"><strong>${esc(state.compare.recommendation)}</strong><p>Previous score: ${state.compare.previousScore} • Current score: ${state.compare.currentScore} • Fixed: ${state.compare.fixedCount} • New issues: ${state.compare.newIssueCount}</p></div>`}else $('compareBox').classList.add('hidden')}
function renderHistory(){const h=Storage.history();$('history').innerHTML=h.length?h.slice(0,6).map(x=>`<div class="history-item"><strong>${esc(x.meta.type)}</strong><div class="small">${new Date(x.createdAt).toLocaleString()} • Score ${x.score}</div></div>`).join(''):'<div class="small">No previous audits saved on this device.</div>'}
function buildReport(){const a=state.audit;if(!a)return'No audit has been run yet.';let s=`DEBOOGER2000 AUDIT\n\nWHAT THIS IS\n${a.meta.type}\n${a.meta.fileCount} files, ${a.meta.pageCount} pages\n\nSCORE\n${a.score}/100 — ${a.verdict}\n\nGOOD\n${a.good.map(x=>'• '+x).join('\n')||'• No positive checks recorded'}\n\nWHAT NEEDS ATTENTION\n`;s+=a.findings.map((f,i)=>`${i+1}. ${f.title}\n   ${f.plain}${f.file?`\n   File: ${f.file}${f.line?` line ${f.line}`:''}`:''}`).join('\n\n')||'No obvious issues found.';if(state.compare)s+=`\n\nVERSION COMPARISON\n${state.compare.recommendation}\nPrevious: ${state.compare.previousScore} | Current: ${state.compare.currentScore}`;return s}
async function copyReport(){try{await navigator.clipboard.writeText(buildReport());status('Copied')}catch{const ta=document.createElement('textarea');ta.value=buildReport();document.body.appendChild(ta);ta.select();document.execCommand('copy');ta.remove();status('Copied')}}
function downloadReport(){const b=new Blob([buildReport()],{type:'text/plain'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='debooger2000-audit.txt';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function renderProviders(){const p=loadProviderSettings();$('groqEnabled').checked=!!p.groq?.enabled;$('groqKey').value=p.groq?.key||'';$('googleEnabled').checked=!!p.google?.enabled;$('googleKey').value=p.google?.key||'';$('providerStatus').textContent=providerSummary(p)}
function saveProviders(){const p={groq:{enabled:$('groqEnabled').checked,key:$('groqKey').value.trim()},google:{enabled:$('googleEnabled').checked,key:$('googleKey').value.trim()}};saveProviderSettings(p);$('providerStatus').textContent=providerSummary(p);status('AI settings saved locally')}
window.addEventListener('message',e=>{if(e.data?.type==='debooger-nav'){const p=norm(resolve(e.data.base,e.data.href));if(runtime.files.has(p))select(p)}if(e.data?.type==='debooger-runtime-error'){state.runtimeErrors.push(e.data);status('Runtime issue captured')}});
['dragenter','dragover'].forEach(v=>$('dropzone').addEventListener(v,e=>{e.preventDefault();$('dropzone').classList.add('drag')}));['dragleave','drop'].forEach(v=>$('dropzone').addEventListener(v,e=>{e.preventDefault();$('dropzone').classList.remove('drag')}));$('dropzone').addEventListener('drop',e=>addFiles(e.dataTransfer.files));$('fileInput').onchange=e=>addFiles(e.target.files);$('folderInput').onchange=e=>addFiles(e.target.files);$('openBtn').onclick=()=>$('fileInput').click();$('auditBtn').onclick=runAudit;$('copyBtn').onclick=copyReport;$('downloadBtn').onclick=downloadReport;$('adaptToggle').onchange=()=>setDevice(state.mode);$('saveProviders').onclick=saveProviders;document.querySelectorAll('.device-btn').forEach(b=>b.onclick=()=>setDevice(b.dataset.device));window.addEventListener('resize',fit);renderHistory();renderProviders();applyDevice();frame.srcdoc='<html><body style="font-family:Inter,system-ui;padding:42px"><h1>debooger2000</h1><p>Drop a project to reconstruct, preview, audit and compare it.</p></body></html>';
