const MIME={html:'text/html',htm:'text/html',css:'text/css',js:'text/javascript',mjs:'text/javascript',jsx:'text/jsx',tsx:'text/tsx',ts:'text/typescript',json:'application/json',txt:'text/plain',md:'text/markdown',csv:'text/csv',xml:'application/xml',svg:'image/svg+xml',png:'image/png',jpg:'image/jpeg',jpeg:'image/jpeg',gif:'image/gif',webp:'image/webp',bmp:'image/bmp',ico:'image/x-icon',pdf:'application/pdf',zip:'application/zip',woff:'font/woff',woff2:'font/woff2',ttf:'font/ttf',otf:'font/otf'};
export const norm=p=>String(p||'').replaceAll('\\','/').replace(/^\.\//,'').replace(/^\//,'');
export const ext=n=>{const i=n.lastIndexOf('.');return i<0?'':n.slice(i+1).toLowerCase()};
export const mime=n=>MIME[ext(n)]||'application/octet-stream';
export function classify(files){const names=[...files.keys()].map(n=>n.toLowerCase());const has=n=>names.some(x=>x===n||x.endsWith('/'+n));let type='Mixed project',runtime='Browser';if(has('package.json')){if(names.some(x=>x.includes('electron'))||has('electron.js')||has('main.cjs'))type='Electron application';else if(names.some(x=>x.includes('vite.config')))type='Vite web application';else if(names.some(x=>x.includes('next.config')))type='Next.js application';else if(names.some(x=>x.endsWith('.jsx')||x.endsWith('.tsx')))type='React/Node application';else type='Node/JavaScript application'}else if(names.some(n=>n.endsWith('.html')||n.endsWith('.htm')))type=names.filter(n=>/\.html?$/.test(n)).length>1?'Multi-page website':'HTML website';else if(names.some(n=>/\.(jsx|tsx)$/.test(n)))type='React-style source project';else if(names.some(n=>n.endsWith('.py')))type='Python project';if(type.includes('Electron'))runtime='Desktop runtime + browser-style interface';else if(type.includes('Next')||type.includes('Node')||type.includes('React/Node'))runtime='Build/server runtime';else if(type.includes('Python'))runtime='Python runtime';const pages=names.filter(n=>/\.html?$/.test(n));return{type,runtime,fileCount:names.length,pageCount:pages.length,pages};}
function dirname(p){const i=p.lastIndexOf('/');return i>=0?p.slice(0,i+1):''}
export function resolve(base,ref){if(!ref||/^(data:|blob:|https?:|mailto:|tel:|javascript:|#)/i.test(ref))return ref;const a=dirname(base).split('/').filter(Boolean);for(const x of ref.split('/')){if(!x||x==='.')continue;if(x==='..')a.pop();else a.push(x)}return a.join('/')}
function splitSrcset(value){return String(value||'').split(',').map(x=>x.trim()).filter(Boolean).map(part=>{const bits=part.split(/\s+/);return{url:bits.shift(),descriptor:bits.join(' ')}})}
export class ProjectRuntime{
  constructor(){this.files=new Map();this.urls=new Map()}
  clear(){for(const u of this.urls.values())URL.revokeObjectURL(u);this.urls.clear();this.files.clear()}
  async addFiles(list){this.clear();const out=[];for(const f of [...list]){if(ext(f.name)==='zip'){if(typeof JSZip==='undefined')throw new Error('ZIP support did not load. Check the internet connection and try again.');const z=await JSZip.loadAsync(f);for(const zf of Object.values(z.files).filter(x=>!x.dir&&!/^__MACOSX\//i.test(x.name))){const b=await zf.async('blob');out.push(new File([b],norm(zf.name),{type:mime(zf.name)}))}}else{const n=f.webkitRelativePath||f.name;out.push(new File([f],norm(n),{type:f.type||mime(n)}))}}for(const f of out)this.files.set(norm(f.name),f);return out}
  entry(){const n=[...this.files.keys()];return['index.html','index.htm','dist/index.html','build/index.html','public/index.html','src/index.html'].find(p=>n.includes(p))||n.find(x=>/(^|\/)index\.html?$/i.test(x))||n.find(x=>/\.html?$/i.test(x))||n[0]}
  async objectUrl(path){path=norm(path);if(this.urls.has(path))return this.urls.get(path);const f=this.files.get(path);if(!f)return null;const u=URL.createObjectURL(f);this.urls.set(path,u);return u}
  async cssRewrite(css,base,seen=new Set()){if(seen.has(base))return css;seen.add(base);for(const m of [...css.matchAll(/@import\s+(?:url\()?['"]?([^'"\);\s]+)['"]?\)?\s*;?/gi)]){const p=norm(resolve(base,m[1])),f=this.files.get(p);if(f){const imported=await this.cssRewrite(await f.text(),p,seen);css=css.replace(m[0],`\n/* combined from ${p} */\n${imported}\n`)}}for(const m of [...css.matchAll(/url\((['"]?)([^'"\)]+)\1\)/g)]){const ref=m[2].trim();if(/^(data:|blob:|https?:|#)/i.test(ref))continue;const u=await this.objectUrl(resolve(base,ref));if(u)css=css.split(m[0]).join(`url("${u}")`)}return css}
  async htmlRewrite(src,base,inject=''){const d=new DOMParser().parseFromString(src,'text/html');
    for(const l of [...d.querySelectorAll('link[rel="stylesheet"][href]')]){const p=norm(resolve(base,l.getAttribute('href'))),f=this.files.get(p);if(f){const st=d.createElement('style');st.setAttribute('data-debooger-source',p);st.textContent=await this.cssRewrite(await f.text(),p);l.replaceWith(st)}}
    for(const l of [...d.querySelectorAll('link[href]')]){if((l.getAttribute('rel')||'').toLowerCase()==='stylesheet')continue;const ref=l.getAttribute('href'),u=await this.objectUrl(resolve(base,ref));if(u)l.setAttribute('href',u)}
    for(const el of [...d.querySelectorAll('[src],[poster]')])for(const a of ['src','poster']){const r=el.getAttribute(a);if(!r)continue;const u=await this.objectUrl(resolve(base,r));if(u)el.setAttribute(a,u)}
    for(const el of [...d.querySelectorAll('[srcset]')]){const parts=splitSrcset(el.getAttribute('srcset')),next=[];for(const item of parts){const u=await this.objectUrl(resolve(base,item.url));next.push(`${u||item.url}${item.descriptor?' '+item.descriptor:''}`)}if(next.length)el.setAttribute('srcset',next.join(', '))}
    for(const el of [...d.querySelectorAll('[style]')])el.setAttribute('style',await this.cssRewrite(el.getAttribute('style'),base));
    for(const s of [...d.querySelectorAll('script[src]')]){const p=norm(resolve(base,s.getAttribute('src'))),f=this.files.get(p);if(f){const ns=d.createElement('script');ns.textContent=await f.text();for(const a of [...s.attributes])if(a.name!=='src')ns.setAttribute(a.name,a.value);ns.setAttribute('data-debooger-source',p);s.replaceWith(ns)}}
    const nav=d.createElement('script');nav.textContent=`document.addEventListener('click',e=>{const a=e.target.closest('a[href]');if(!a)return;const h=a.getAttribute('href')||'';if(h&&!/^(https?:|mailto:|tel:|javascript:|#)/i.test(h)){e.preventDefault();parent.postMessage({type:'debooger-nav',href:h,base:${JSON.stringify(base)}},'*')}});window.addEventListener('error',e=>parent.postMessage({type:'debooger-runtime-error',message:e.message,line:e.lineno,col:e.colno},'*'));window.addEventListener('unhandledrejection',e=>parent.postMessage({type:'debooger-runtime-error',message:'Promise rejection: '+String(e.reason?.message||e.reason||'unknown')},'*'));`;d.body.appendChild(nav);
    if(inject)d.head.insertAdjacentHTML('beforeend',inject);return '<!doctype html>\n'+d.documentElement.outerHTML}
}
