import { chromium } from 'playwright';
import JSZip from 'jszip';
import assert from 'node:assert/strict';

const zip = new JSZip();
zip.file('index.html', '<!doctype html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Fixture</title></head><body><div id="root"></div><script type="module" src="/src/main.tsx"></script></body></html>');
zip.file('package.json', JSON.stringify({dependencies:{react:'^19.0.1','react-dom':'^19.0.1',tailwindcss:'^4.1.14','@tailwindcss/vite':'^4.1.14'},devDependencies:{'@vitejs/plugin-react':'^5.0.4'},scripts:{build:'vite build'}}));
zip.file('vite.config.ts', 'export default {}');
zip.file('src/main.tsx', `import React from 'react'; import {createRoot} from 'react-dom/client'; import './index.css'; import App from './App'; createRoot(document.getElementById('root')!).render(<App/>);`);
zip.file('src/App.tsx', `import React,{useState} from 'react'; export default function App(){const [open,setOpen]=useState(false);return <main className="bg-slate-900 text-white p-4"><h1>REAL REACT SCREEN</h1><button aria-haspopup="true" onClick={()=>setOpen(v=>!v)}>Settings</button>{open&&<div role="dialog">OPENED SETTINGS</div>}</main>}`);
zip.file('src/index.css', '@import "tailwindcss"; body{margin:0}');
const buffer = await zip.generateAsync({type:'nodebuffer'});
const browser = await chromium.launch({headless:true});
const page = await browser.newPage({viewport:{width:390,height:844}});
const errors=[]; page.on('pageerror',e=>errors.push(String(e)));
await page.goto('http://127.0.0.1:4173/index.html',{waitUntil:'domcontentloaded'});
await page.setInputFiles('#fileInput',{name:'fixture.zip',mimeType:'application/zip',buffer});
await page.waitForTimeout(12000);
assert.equal(await page.locator('#pasteBtn').isVisible(),false,'Paste must be hidden from mobile top bar');
assert.equal(await page.locator('#clearBtn').isVisible(),false,'Clear must be hidden from mobile top bar');
assert.equal(await page.locator('#moreBtn').isVisible(),true,'More button must be visible on mobile');
const frame=page.frames().find(f=>f!==page.mainFrame());
assert(frame,'preview iframe must exist');
await frame.waitForSelector('text=REAL REACT SCREEN',{timeout:15000});
const bg=await frame.locator('main').evaluate(el=>getComputedStyle(el).backgroundColor);
assert.notEqual(bg,'rgba(0, 0, 0, 0)','Tailwind styles should render');
await page.locator('#fullBtn').click();
await page.waitForTimeout(300);
assert.equal(await page.locator('main.main').evaluate(el=>el.classList.contains('viewer-full')),true,'full screen fallback class must activate');
await page.locator('#exitFullBtn').click();
await page.waitForTimeout(300);
await page.waitForFunction(()=>document.getElementById('shotCount')?.textContent!=='0',{timeout:25000});
assert(Number(await page.locator('#shotCount').textContent())>0,'audit must capture real screenshots');
await page.locator('#openResultsBtn').click();
assert.equal(await page.locator('#resultsModal').isVisible(),true,'mobile results must open');
await page.locator('.files-card summary').click();
assert((await page.locator('#fileList').innerText()).includes('src/App.tsx'),'full file path must be visible');
assert((await page.locator('#fileList').innerText()).includes('Program code'),'simple file explanation must be visible');
if(errors.length) throw new Error('Page errors: '+errors.join(' | '));
await browser.close();
console.log('BUILD002_RUNTIME_PASS');